server:
    port: 8888
    context-path: /hrms

logging:
    level:
        com.dy.springboot.server.mapper: DEBUG
        # com.onepro.custom.mapper: DEBUG
        com.dlts.hrms.mapper: DEBUG
        tk.mybatis: DEBUG

spring:
    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
        name: test
        url: jdbc:mysql://192.168.183.131:3306/hrms?characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .html

#以下属性不可用
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: tk.mybatis.springboot.util.MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: tk.mybatis.springboot.model
#    mapperScanner:
#        basePackage: tk.mybatis.springboot.mapper
